; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F103RC]
platform = ststm32
board = genericSTM32F103RC
framework = arduino
upload_protocol = stlink
debug_protocol = stlink
monitor_speed = 115200
lib_deps = bodmer/TFT_eSPI@^2.5.43
build_flags = 
	-finput-charset=UTF-8
	-fexec-charset=UTF-8
	-DUSER_SETUP_LOADED
	-DSTM32
	-DTFT_PARALLEL_8_BIT
	-DSTM_PORTB_DATA_BUS
	-DILI9488_DRIVER
	-DTFT_DC=PA2
	-DTFT_CS=PA4
	-DTFT_WR=PA5
	-DTFT_RD=PA3
	-DTFT_RST=PA1
	-DTFT_D0=PB0
	-DTFT_D1=PB1
	-DTFT_D2=PB2
	-DTFT_D3=PB3
	-DTFT_D4=PB4
	-DTFT_D5=PB5
	-DTFT_D6=PB6
	-DTFT_D7=PB7
	-DTFT_D8=PB8
	-DTFT_D9=PB9
	-DTFT_D10=PB10
	-DTFT_D11=PB11
	-DTFT_D12=PB12
	-DTFT_D13=PB13
	-DTFT_D14=PB14
	-DTFT_D15=PB15
	-DLOAD_GLCD
	-DLOAD_FONT2
	-DLOAD_FONT4
	-DLOAD_FONT6
	-DLOAD_FONT7
	-DLOAD_FONT8
	-DLOAD_GFXFF
	-DSMOOTH_FONT
	-DTFT_16BIT_BUS
